/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Hello */

#ifndef _Included_Hello
#define _Included_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Hello
 * Method:    jniSayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Hello_jniSayHello__
  (JNIEnv *, jobject);

/*
 * Class:     Hello
 * Method:    jniSayHello
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Hello_jniSayHello__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     Hello
 * Method:    jniSayClass
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_Hello_jniSayClass
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Hello
 * Method:    jniLoadObject
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_Hello_jniLoadObject
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
